import React, { useState } from "react";
import { Download, CheckCircle, Clock, Award, ListTodo, Sparkles } from "lucide-react";

interface Habit { id: string; label: string; done: boolean; xpReward: number; }

export default function LifeOSPanel({ branchId, roleId }: { branchId?: string | null; roleId?: string | null }) {
  const branch = branchId || "CSE";
  const role = roleId || "Software Engineer";

  // Habit Tracker State
  const [habits, setHabits] = useState<Habit[]>([
    { id: "dsa", label: "Solve 1 DSA coding question", done: false, xpReward: 15 },
    { id: "quant", label: "Solve 5 Quantitative Aptitude sums", done: false, xpReward: 10 },
    { id: "mock", label: "Review 10 mock placement questions", done: false, xpReward: 10 },
    { id: "english", label: "Spend 10 mins practicing verbal mock interviews", done: false, xpReward: 10 },
    { id: "resume", label: "Revise keywords for target MNC requirements", done: false, xpReward: 10 },
  ]);

  // Planner Inputs
  const [dailyHours, setDailyHours] = useState("4");
  const [timeline, setTimeline] = useState("3"); // months
  const [generatedPlan, setGeneratedPlan] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);

  const toggleHabit = (id: string) => {
    setHabits(prev => prev.map(h => h.id === id ? { ...h, done: !h.done } : h));
  };

  const completedCount = habits.filter(h => h.done).length;
  const disciplineScore = Math.round((completedCount / habits.length) * 100);

  const handleGeneratePlan = () => {
    setGenerating(true);
    setTimeout(() => {
      const hours = parseInt(dailyHours, 10);
      const m = parseInt(timeline, 10);
      const totalDays = m * 30;

      // Allocate hours dynamically based on user input
      const dsaHrs = Math.round(hours * 0.45 * 10) / 10;
      const quantHrs = Math.round(hours * 0.25 * 10) / 10;
      const coreHrs = Math.round(hours * 0.20 * 10) / 10;
      const verbalHrs = Math.round(hours * 0.10 * 10) / 10;

      const planText = `
# 📅 LIFE OS: PERSONALIZED PLACEMENT PREPARATION SCHEDULE
**Target Branch:** ${branch.toUpperCase()} | **Target Role:** ${role}
**Daily Preparation Capacity:** ${hours} Hours/day | **Timeline Goal:** ${m} Months (${totalDays} Days)

---

## 🕒 DAILY STUDY TIME ALLOCATION
Here is your optimized daily hour breakdown generated by Life OS AI:

1. 💻 **Data Structures & Algorithms (DSA):** ${dsaHrs} Hours
   - Focus areas: Arrays, sliding window, recursion, dynamic programming, and binary search.
2. 📖 **Quantitative & Logical Aptitude:** ${quantHrs} Hours
   - Focus areas: Number systems, percentages, ratios, time & work, and seating arrangements.
3. ⚙️ **Department Core & Memory Models:** ${coreHrs} Hours
   - Focus areas: Operating system CPU scheduling, database indexes/SQL joins, and OOP memory patterns.
4. 🗣️ **Verbal Ability & ATS Optimization:** ${verbalHrs} Hours
   - Focus areas: Mock HR answers, STAR technique responses, grammar error spotting, and resume tailoring.

---

## 🎯 TIMELINE STRATEGY (${m}-Month Road Checkpoints)

### 🏁 Month 1: Fundamentals & Foundation
- Complete Phase 1 (Aptitude Foundation) lessons.
- Solve 30 easy coding questions.
- Draft your master resume template in the **Resume & ATS** workspace.

### 📈 Month 2: Core Engineering & DSA Depth
- Complete Phase 2 & 3 modules.
- Practice intermediate coding questions on arrays, trees, and linked lists.
- Set up your GitHub portfolio page using the **Portfolio Creator**.

### 🏆 Month 3: Placement Certification & Mock Rounds
- Clear the Grand Boss exam in Phase 5.
- Generate mock tests inside the **Maahir AI** workspace.
- Tailor individual resumes for target companies (Google, Amazon, TCS).
      `.trim();

      setGeneratedPlan(planText);
      setGenerating(false);
    }, 800);
  };

  const downloadPlan = () => {
    if (!generatedPlan) return;
    const blob = new Blob([generatedPlan], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Life_OS_Study_Plan_${branch}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      {/* Left: AI Habit Tracker & Discipline Score */}
      <div className="space-y-6">
        <div className="p-6 rounded-3xl border border-border bg-white/5 space-y-4">
          <div className="flex justify-between items-center">
            <h3 className="text-lg font-display flex items-center gap-2">
              <ListTodo className="text-cyan-400" size={22} /> Daily Placement Habits
            </h3>
            <span className="text-xs font-bold text-slate-400 font-mono">Discipline: {disciplineScore}%</span>
          </div>

          <div className="w-full bg-slate-800 h-2 rounded-full overflow-hidden">
            <div className="bg-gradient-to-r from-cyan-500 to-blue-500 h-full transition-all duration-300" style={{ width: `${disciplineScore}%` }} />
          </div>

          <div className="space-y-2.5">
            {habits.map(h => (
              <button
                key={h.id}
                onClick={() => toggleHabit(h.id)}
                className={`w-full p-4 rounded-2xl border text-left text-xs font-semibold transition-all flex items-center justify-between ${
                  h.done
                    ? "bg-cyan-500/10 border-cyan-500/40 text-cyan-300"
                    : "bg-black/20 border-white/5 text-slate-400 hover:border-white/10 hover:text-slate-300"
                }`}
              >
                <span className="flex items-center gap-2.5">
                  <CheckCircle size={16} className={h.done ? "text-cyan-400" : "text-slate-600"} />
                  {h.label}
                </span>
                <span className="text-[10px] text-amber-400 font-mono">+{h.xpReward} XP</span>
              </button>
            ))}
          </div>
        </div>

        {/* Milestone Targets */}
        <div className="p-6 rounded-3xl border border-border bg-white/5 space-y-4">
          <h3 className="text-sm font-bold text-purple-400 flex items-center gap-1.5">
            <Award size={16} /> Key Placement Checkpoints
          </h3>
          <div className="space-y-3 font-mono text-xs">
            <div className="flex items-center justify-between p-3 rounded-xl bg-black/20 border border-white/5">
              <span>1. Resume Completed & Keyword Analyzed</span>
              <span className="text-cyan-400 font-bold">READY</span>
            </div>
            <div className="flex items-center justify-between p-3 rounded-xl bg-black/20 border border-white/5">
              <span>2. Portfolio Created & Host-Ready</span>
              <span className="text-cyan-400 font-bold">READY</span>
            </div>
            <div className="flex items-center justify-between p-3 rounded-xl bg-black/20 border border-white/5">
              <span>3. All 5 Syllabus Phases Cleared</span>
              <span className="text-purple-400 font-bold">PROGRESS</span>
            </div>
          </div>
        </div>
      </div>

      {/* Right: AI Study Planner Generator */}
      <div className="space-y-6">
        <div className="p-6 rounded-3xl border border-border bg-white/5 space-y-4">
          <h3 className="text-lg font-display flex items-center gap-2">
            <Clock className="text-purple-400" size={22} /> AI Routine & Schedule Generator
          </h3>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1">
              <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Study Capacity / Day</label>
              <select
                value={dailyHours}
                onChange={e => setDailyHours(e.target.value)}
                className="w-full bg-black/30 border border-white/10 rounded-xl px-3 py-2.5 text-xs text-white focus:outline-none focus:border-purple-400"
              >
                <option value="2">2 Hours</option>
                <option value="4">4 Hours</option>
                <option value="6">6 Hours</option>
                <option value="8">8 Hours</option>
              </select>
            </div>
            <div className="space-y-1">
              <label className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Months to Placement</label>
              <select
                value={timeline}
                onChange={e => setTimeline(e.target.value)}
                className="w-full bg-black/30 border border-white/10 rounded-xl px-3 py-2.5 text-xs text-white focus:outline-none focus:border-purple-400"
              >
                <option value="1">1 Month</option>
                <option value="3">3 Months</option>
                <option value="6">6 Months</option>
              </select>
            </div>
          </div>

          <button
            onClick={handleGeneratePlan}
            disabled={generating}
            className="w-full py-3 rounded-full bg-gradient-to-r from-purple-500 to-cyan-500 hover:from-purple-600 hover:to-cyan-600 font-bold text-sm transition-all text-white flex items-center justify-center gap-1.5"
          >
            <Sparkles size={16} />
            {generating ? "Calculating Schedules..." : "Generate AI Study Plan"}
          </button>
        </div>

        {generatedPlan && (
          <div className="p-6 rounded-3xl border border-border bg-white/5 space-y-4">
            <div className="flex justify-between items-center">
              <h4 className="text-xs font-bold text-emerald-400 uppercase tracking-wider">Generated Timetable</h4>
              <button
                onClick={downloadPlan}
                className="text-xs px-3 py-1.5 rounded-lg border border-emerald-500/30 hover:bg-emerald-500/10 text-emerald-400 font-bold flex items-center gap-1.5"
              >
                <Download size={12} /> Download Plan
              </button>
            </div>
            <pre className="text-xs text-slate-300 leading-relaxed font-mono whitespace-pre-wrap max-h-[300px] overflow-y-auto p-4 rounded-xl bg-black/40 border border-white/5 custom-scrollbar">
              {generatedPlan}
            </pre>
          </div>
        )}
      </div>
    </div>
  );
}
